apiVersion: v1
kind: Service
metadata:
  name: stockops-api
  namespace: stockops
  labels:
    app: stockops-api
spec:
  type: ClusterIP
  selector:
    app: stockops-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
