apiVersion: v1
kind: Service
metadata:
  name: stockops-admin-web
  namespace: stockops
  labels:
    app: stockops-admin-web
spec:
  type: ClusterIP
  selector:
    app: stockops-admin-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
